// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ-MoE6AAsWagxnMwF46d-9DYmStaHvNw',
    appId: '1:267523114213:android:455013cae73730b99f800c',
    messagingSenderId: '267523114213',
    projectId: 'widgetpracice',
    storageBucket: 'widgetpracice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZTYeZDRhXbqn4G592JwRBRkL5586UUXs',
    appId: '1:267523114213:ios:dbab4ad040703fab9f800c',
    messagingSenderId: '267523114213',
    projectId: 'widgetpracice',
    storageBucket: 'widgetpracice.appspot.com',
    androidClientId: '267523114213-5cvd9pk26db9u77dm76354h94fhvbomn.apps.googleusercontent.com',
    iosClientId: '267523114213-45ubm7ehis0635s9ua4oulmqs62mi00e.apps.googleusercontent.com',
    iosBundleId: 'com.example.widgetpractice',
  );
}
